version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
      - PORT=${PORT}
